server:
  port: 8989

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: D8604CD49AC
    url: jdbc:p6spy:mysql://localhost:3306/blog?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai


blog:
  # hexo文件夹在服务器上的目录
  hexo-path: /root/myblog
  # 图片上传的资源地址，可以使用阿里oss提供的域名，也可配自有域名
  static-host: https://static.peihuan.net/
  ali:
    access-key-id: LTAI4xxxxxxxxxxxxxxxx
    access-key-secret: 6HQxxxxxxxxxxxxxx
    oss:
      endpoint: http://oss-cn-hangzhou.aliyuncs.com
      # 桶名称
      bucket-name: your-bucket
    cnd:
      # 可用区id https://help.aliyun.com/knowledge_detail/40654.html?spm=5176.13910061.0.0.75ca1477FdcLAM&aly_as=L5ikbwPc
      regionId: cn-hangzhou
      # 博客首页的域名
      host: www.peihuan.net
